# veri analizi, veri manipülasyonu, görselleştirme
## pandas
dilimleme, indeksleme,
koşul ile erişim
veride tip dönüşümü, fonksiyon yazarak dönüşüm
gruplama
merge ve join
eksik veri yönetimi, doldurma yöntemleri
sütun-korelasyon analizi
## numpy
mean, median, min, max, mode, sum, count
dikey-yatay array birleştirme
çok boyutlu arrayde dilimleme, indeksleme, boyut (shape) değişimi
## veri görselleştirme (matplotlib, seaborn, plot.ly)
histogram / dağılım grafiği, çizgi grafiği / line plot, saçılım / scatter, çubuk grafik / bar plot
kutu grafiği / box plot (outlier analizi)
keman / violin plot ()
ısı haritası / heatmap
3 boyutlu grafikler

In [ ]:
import numpy as np
import pandas as pd


# numpy

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
for i in range(3,10): # iterable
    print(i)
list(range(3,10))

3
4
5
6
7
8
9


[3, 4, 5, 6, 7, 8, 9]

In [ ]:
a = np.arange(3,11)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a + 4

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
a = a.reshape(4,2)
a

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
a.shape #a.ndim

(4, 2)

In [ ]:
a >= 7  # 4 işlem, ve mantıksal operatörler

array([[False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
a = np.arange(10,100)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
a.reshape(10, -1) # -1 kendi belirliyor

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a = a.reshape(-1, 9)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
b = a.ravel().reshape(5, 6, 3)
b

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54],
        [55, 56, 57],
        [58, 59, 60],
        [61, 62, 63]],

       [[64, 65, 66],
        [67, 68, 69],
        [70, 71, 72],
        [73, 74, 75],
        [76, 77, 78],
        [79, 80, 81]],

       [[82, 83, 84],
        [85, 86, 87],
        [88, 89, 90],
        [91, 92, 93],
        [94, 95, 96],
        [97, 98, 99]]])

In [ ]:
b.ndim

3

In [ ]:
b.shape

(5, 6, 3)

In [ ]:
b = b.ravel()
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
b.min()

10

In [ ]:
b.max()

99

In [ ]:
b.mean()

54.5

In [ ]:
np.median(b)

54.5

In [ ]:
np.argmin(b)

0

In [ ]:
np.argmax(b)

89

In [ ]:
np.linspace(2, 5, 10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [ ]:
ran = np.random.random_integers(10, 20, 100)


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  """Entry point for launching an IPython kernel.


In [ ]:
ran

array([17, 12, 20, 10, 15, 20, 13, 17, 17, 19, 20, 12, 16, 12, 13, 11, 12,
       20, 18, 14, 14, 11, 19, 13, 19, 18, 13, 11, 11, 13, 17, 15, 12, 14,
       14, 14, 13, 14, 15, 12, 18, 16, 17, 20, 18, 10, 17, 12, 13, 16, 12,
       18, 12, 13, 19, 16, 17, 15, 16, 18, 14, 15, 10, 15, 20, 14, 13, 16,
       19, 16, 11, 18, 17, 15, 18, 11, 15, 10, 10, 13, 13, 18, 12, 17, 13,
       15, 14, 19, 17, 18, 11, 10, 13, 16, 12, 18, 11, 15, 13, 10])

In [ ]:
a = np.ones(10).reshape(5, 2)
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
b = np.zeros(10).reshape(5,2)
b

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.hstack((a, b))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [ ]:
np.vstack((a, b))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
ran.sort()

In [ ]:
ran

array([10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20])

In [ ]:
?np.sort

In [ ]:
?open

In [ ]:
a = [1,2,3,4,5]
b = a
b.append(100)
a

[1, 2, 3, 4, 5, 100]

In [ ]:
a = [1,2,3,4,5]
b = a.copy()  # içeriğini kopyalar
b.append(100)
a

[1, 2, 3, 4, 5]

In [ ]:
ran

array([10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20])

In [ ]:
ran[3:7]

array([10, 10, 10, 10])

In [ ]:
c = ran.reshape(20, -1)
c

array([[10, 10, 10, 10, 10],
       [10, 10, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [14, 14, 14, 14, 14],
       [14, 14, 14, 14, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 16],
       [16, 16, 16, 16, 16],
       [16, 16, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 19, 19],
       [19, 19, 19, 19, 20],
       [20, 20, 20, 20, 20]])

In [ ]:
c[1]

array([10, 10, 11, 11, 11])

In [ ]:
c[1][-10: -6]

array([], dtype=int64)

In [ ]:
c[3:6,1:4]

array([[12, 12, 12],
       [12, 12, 12],
       [13, 13, 13]])

# pandas

In [ ]:
import pandas as pd
import seaborn as sns

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
tips_orj = sns.load_dataset("tips")
tips = tips_orj.copy()
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(tips, *['total_bill'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(tips, *['tip'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(tips, *['size'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(tips, *['total_bill'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(tips, *['tip'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(tips, *['size'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plots(df, colname_pairs, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * 6 * figscale, 6 * figscale))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha, ax=ax)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(tips, *[[['total_bill', 'tip'], ['tip', 'size']]], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(tips, *['time', 'total_bill', None], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(tips, *['time', 'tip', None], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(tips, *['time', 'size', None], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(tips, *['time', 'count()', None], **{})
chart

In [ ]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [ ]:
tips.size / 7

244.0

In [ ]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
tips["size"]

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [ ]:
tips.smoker

0       No
1       No
2       No
3       No
4       No
      ... 
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): [Yes, No]

In [ ]:
tips.size

1708

In [ ]:
np.max(tips["size"])

6

In [ ]:
tips["size"].max()

6

In [ ]:
np.std(tips["size"])

0.9491488287193913

In [ ]:
np.mean(tips["size"])

2.569672131147541

In [ ]:
tips["smoker"].mode()

0    No
Name: smoker, dtype: category
Categories (2, object): [Yes, No]

In [ ]:
%time
tips.smoker

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 9.3 µs


0       No
1       No
2       No
3       No
4       No
      ... 
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): [Yes, No]

In [ ]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips.tail(3)

total_bill   tip     sex smoker   day    time  size
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
list(tips.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [ ]:
tips.describe(include="all").T # quartile / kartil Q1, Q2,...

count unique     top freq     mean      std   min      25%     50%  \
total_bill   244    NaN     NaN  NaN  19.7859  8.90241  3.07  13.3475  17.795   
tip          244    NaN     NaN  NaN  2.99828  1.38364     1        2     2.9   
sex          244      2    Male  157      NaN      NaN   NaN      NaN     NaN   
smoker       244      2      No  151      NaN      NaN   NaN      NaN     NaN   
day          244      4     Sat   87      NaN      NaN   NaN      NaN     NaN   
time         244      2  Dinner  176      NaN      NaN   NaN      NaN     NaN   
size         244    NaN     NaN  NaN  2.56967   0.9511     1        2       2   

                75%    max  
total_bill  24.1275  50.81  
tip          3.5625     10  
sex             NaN    NaN  
smoker          NaN    NaN  
day             NaN    NaN  
time            NaN    NaN  
size              3      6

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tips["hesap tl"] = tips["total_bill"] * 7.8
tips

total_bill   tip     sex smoker   day    time  size  hesap tl
0         16.99  1.01  Female     No   Sun  Dinner     2   132.522
1         10.34  1.66    Male     No   Sun  Dinner     3    80.652
2         21.01  3.50    Male     No   Sun  Dinner     3   163.878
3         23.68  3.31    Male     No   Sun  Dinner     2   184.704
4         24.59  3.61  Female     No   Sun  Dinner     4   191.802
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3   226.434
240       27.18  2.00  Female    Yes   Sat  Dinner     2   212.004
241       22.67  2.00    Male    Yes   Sat  Dinner     2   176.826
242       17.82  1.75    Male     No   Sat  Dinner     2   138.996
243       18.78  3.00  Female     No  Thur  Dinner     2   146.484

[244 rows x 8 columns]

In [ ]:
#tips["total_bill"] = tips["total_bill"].mean()

19.78594262295082

# indexing / slicing

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size  hesap tl
0         16.99  1.01  Female     No   Sun  Dinner     2   132.522
1         10.34  1.66    Male     No   Sun  Dinner     3    80.652
2         21.01  3.50    Male     No   Sun  Dinner     3   163.878
3         23.68  3.31    Male     No   Sun  Dinner     2   184.704
4         24.59  3.61  Female     No   Sun  Dinner     4   191.802
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3   226.434
240       27.18  2.00  Female    Yes   Sat  Dinner     2   212.004
241       22.67  2.00    Male    Yes   Sat  Dinner     2   176.826
242       17.82  1.75    Male     No   Sat  Dinner     2   138.996
243       18.78  3.00  Female     No  Thur  Dinner     2   146.484

[244 rows x 8 columns]

In [ ]:
tips[0:5]

total_bill   tip     sex smoker  day    time  size  hesap tl
0       16.99  1.01  Female     No  Sun  Dinner     2   132.522
1       10.34  1.66    Male     No  Sun  Dinner     3    80.652
2       21.01  3.50    Male     No  Sun  Dinner     3   163.878
3       23.68  3.31    Male     No  Sun  Dinner     2   184.704
4       24.59  3.61  Female     No  Sun  Dinner     4   191.802

In [ ]:
tips[["size","hesap tl"]]

size  hesap tl
0       2   132.522
1       3    80.652
2       3   163.878
3       2   184.704
4       4   191.802
..    ...       ...
239     3   226.434
240     2   212.004
241     2   176.826
242     2   138.996
243     2   146.484

[244 rows x 2 columns]

In [ ]:
tips.loc[:,:]

total_bill   tip     sex smoker   day    time  size  hesap tl
0         16.99  1.01  Female     No   Sun  Dinner     2   132.522
1         10.34  1.66    Male     No   Sun  Dinner     3    80.652
2         21.01  3.50    Male     No   Sun  Dinner     3   163.878
3         23.68  3.31    Male     No   Sun  Dinner     2   184.704
4         24.59  3.61  Female     No   Sun  Dinner     4   191.802
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3   226.434
240       27.18  2.00  Female    Yes   Sat  Dinner     2   212.004
241       22.67  2.00    Male    Yes   Sat  Dinner     2   176.826
242       17.82  1.75    Male     No   Sat  Dinner     2   138.996
243       18.78  3.00  Female     No  Thur  Dinner     2   146.484

[244 rows x 8 columns]

In [ ]:
tips.loc[50:55,"size":"hesap tl"]

size  hesap tl
50     2    97.812
51     2    80.262
52     4   271.518
53     2    77.532
54     4   199.368
55     2   152.022

In [ ]:
tips.loc[50:55,:]

total_bill   tip     sex smoker  day    time  size  hesap tl
50       12.54  2.50    Male     No  Sun  Dinner     2    97.812
51       10.29  2.60  Female     No  Sun  Dinner     2    80.262
52       34.81  5.20  Female     No  Sun  Dinner     4   271.518
53        9.94  1.56    Male     No  Sun  Dinner     2    77.532
54       25.56  4.34    Male     No  Sun  Dinner     4   199.368
55       19.49  3.51    Male     No  Sun  Dinner     2   152.022

In [ ]:
tips.loc[50:55,"tip":]

tip     sex smoker  day    time  size  hesap tl
50  2.50    Male     No  Sun  Dinner     2    97.812
51  2.60  Female     No  Sun  Dinner     2    80.262
52  5.20  Female     No  Sun  Dinner     4   271.518
53  1.56    Male     No  Sun  Dinner     2    77.532
54  4.34    Male     No  Sun  Dinner     4   199.368
55  3.51    Male     No  Sun  Dinner     2   152.022

In [ ]:
tips.loc[[1,50],"smoker":"time"]

smoker  day    time
1      No  Sun  Dinner
50     No  Sun  Dinner

In [ ]:
tips.loc[[1,5,50],["size","time", "size"]]

size    time  size
1      3  Dinner     3
5      4  Dinner     4
50     2  Dinner     2

In [ ]:
tips.iloc[1:5,1:3]

tip     sex
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female